"""empty message

Revision ID: 2bf92dec5fe
Revises: None
Create Date: 2015-05-08 03:17:02.426976

"""

# revision identifiers, used by Alembic.
revision = '2bf92dec5fe'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('racks', postgresql.JSON(), nullable=True),
    sa.Column('ahus', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperatures')
    ### end Alembic commands ###
